spring:
  datasource:
    url: jdbc:h2:mem:~testdb
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
      console:
        enabled: true
        path: /h2-console
logging:
  level:
    org.jline: DEBUG   # Bu to'g'ri formatda
    root: info





