spring:
    datasource:
      url: 'jdbc:postgresql://localhost:5432/test_migration?currentSchema=sb_flyway'
      username: 'migration'
      password: 'root'
      driver-class-name: org.postgresql.Driver

    flyway:
      enabled: true

