# spring:
 # datasource:
  #  url: jdbc:h2:mem:~
   # username: sa
    #password: sa
  #jpa:
   # show-sql: true
    #hibernate:
     # ddl-auto: update
    #properties:
     # hibernate:
      #  format_sql: true
logging:
      level:
        org:
          jline=DEBUG:
        root: info
spring:
  main:
    banner-mode: off






